version: '3.8'

services:
  # The Redis message queue
  redis:
    image: redis:7-alpine
    container_name: redis

  # The Ollama LLM server
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # The Flask web app (cashier)
  web-app:
    build: .
    container_name: web-app
    ports:
      - "5001:5000"
    depends_on:
      - redis
    command: flask --app app run --host=0.0.0.0

  # The Celery worker (barista)
  # Note: --concurrency=1 ensures sequential task processing to prevent CPU contention
  # This provides predictable 4-5 minute completion times per task
  # See CONCURRENCY.md for details
  worker:
    build: .
    container_name: worker
    depends_on:
      - redis
      - ollama
    volumes:
      - ./data:/app/data
    command: celery -A worker.celery_app worker --loglevel=info --concurrency=1

volumes:
  ollama_data: